In [ ]:
!pip install -e .

In [ ]:
!pip install --upgrade torch

In [1]:
import torch
import torch.onnx

In [2]:
torch.__version__


'1.11.0+cu102'

In [3]:
from uberduck_ml_dev.models.tacotron2 import Tacotron2, Tacotron2ForwardIsInfer, DEFAULTS
from uberduck_ml_dev.data_loader import prepare_input_sequence
from uberduck_ml_dev.vendor.tfcompat.hparam import HParams
from uberduck_ml_dev.models.common import griffin_lim, MelSTFT

In [4]:
vals = DEFAULTS.values()
vals.update(cudnn_enabled=False)
hp = HParams(**vals)
model = Tacotron2ForwardIsInfer(hp)

Not using any style tokens


In [5]:
sd = torch.load("model_store/tacotron2-trebek-arpa-740-01-02-21.pt", map_location="cpu")

In [6]:
model.load_state_dict(sd)

<All keys matched successfully>

In [7]:
input_sequence = prepare_input_sequence(["The quick brown fox jumped over the lazy dog and then pooped in my mouth."], cpu_run=True, arpabet=True)
inputs, input_lengths = input_sequence

In [8]:
from typing import List

input_: List[torch.Tensor] = [inputs, input_lengths, torch.tensor([0]), torch.tensor([])]

In [9]:
output = model.inference(*input_)
# input_[0] = input_[0].type(torch.LongTensor)

mel lengths shape
 0
[ CPUIntType{1} ]
mel lengths shape
 1
[ CPUIntType{1} ]
mel lengths shape
 2
[ CPUIntType{1} ]
mel lengths shape
 3
[ CPUIntType{1} ]
mel lengths shape
 4
[ CPUIntType{1} ]
mel lengths shape
 5
[ CPUIntType{1} ]
mel lengths shape
 6
[ CPUIntType{1} ]
mel lengths shape
 7
[ CPUIntType{1} ]
mel lengths shape
 8
[ CPUIntType{1} ]
mel lengths shape
 9
[ CPUIntType{1} ]
mel lengths shape
 10
[ CPUIntType{1} ]
mel lengths shape
 11
[ CPUIntType{1} ]
mel lengths shape
 12
[ CPUIntType{1} ]
mel lengths shape
 13
[ CPUIntType{1} ]
mel lengths shape
 14
[ CPUIntType{1} ]
mel lengths shape
 15
[ CPUIntType{1} ]
mel lengths shape
 16
[ CPUIntType{1} ]
mel lengths shape
 17
[ CPUIntType{1} ]
mel lengths shape
 18
[ CPUIntType{1} ]
mel lengths shape
 19
[ CPUIntType{1} ]
mel lengths shape
 20
[ CPUIntType{1} ]
mel lengths shape
 21
[ CPUIntType{1} ]
mel lengths shape
 22
[ CPUIntType{1} ]
mel lengths shape
 23
[ CPUIntType{1} ]
mel lengths shape
 24
[ CPUIntType{1} ]
mel length

mel lengths shape
 232
[ CPUIntType{1} ]
mel lengths shape
 233
[ CPUIntType{1} ]
mel lengths shape
 234
[ CPUIntType{1} ]
mel lengths shape
 235
[ CPUIntType{1} ]
mel lengths shape
 236
[ CPUIntType{1} ]
mel lengths shape
 237
[ CPUIntType{1} ]
mel lengths shape
 238
[ CPUIntType{1} ]
mel lengths shape
 239
[ CPUIntType{1} ]
mel lengths shape
 240
[ CPUIntType{1} ]
mel lengths shape
 241
[ CPUIntType{1} ]
mel lengths shape
 242
[ CPUIntType{1} ]
mel lengths shape
 243
[ CPUIntType{1} ]
mel lengths shape
 244
[ CPUIntType{1} ]
mel lengths shape
 245
[ CPUIntType{1} ]
mel lengths shape
 246
[ CPUIntType{1} ]
mel lengths shape
 247
[ CPUIntType{1} ]
mel lengths shape
 248
[ CPUIntType{1} ]
mel lengths shape
 249
[ CPUIntType{1} ]
mel lengths shape
 250
[ CPUIntType{1} ]
mel lengths shape
 251
[ CPUIntType{1} ]
mel lengths shape
 252
[ CPUIntType{1} ]
mel lengths shape
 253
[ CPUIntType{1} ]
mel lengths shape
 254
[ CPUIntType{1} ]
mel lengths shape
 255
[ CPUIntType{1} ]
mel lengths shap

In [10]:
model.eval()
#model.forward = model.inference
#model.encoder.forward = model.encoder.inference
scripted_module = torch.jit.script(model)

In [11]:
for o in output:
    print(o.shape)
stft = MelSTFT()
audio = stft.griffin_lim(output[0][0])
from IPython.display import Audio
Audio(audio, rate=22050)

torch.Size([1, 80, 414])
torch.Size([1, 80, 414])
torch.Size([1, 414])
torch.Size([1, 414, 63])


In [12]:
scripted_module(*input_)

mel lengths shape
 0
[ CPUIntType{1} ]
mel lengths shape
 1
[ CPUIntType{1} ]
mel lengths shape
 2
[ CPUIntType{1} ]
mel lengths shape
 3
[ CPUIntType{1} ]
mel lengths shape
 4
[ CPUIntType{1} ]
mel lengths shape
 5
[ CPUIntType{1} ]
mel lengths shape
 6
[ CPUIntType{1} ]
mel lengths shape
 7
[ CPUIntType{1} ]
mel lengths shape
 8
[ CPUIntType{1} ]
mel lengths shape
 9
[ CPUIntType{1} ]
mel lengths shape
 10
[ CPUIntType{1} ]
mel lengths shape
 11
[ CPUIntType{1} ]
mel lengths shape
 12
[ CPUIntType{1} ]
mel lengths shape
 13
[ CPUIntType{1} ]
mel lengths shape
 14
[ CPUIntType{1} ]
mel lengths shape
 15
[ CPUIntType{1} ]
mel lengths shape
 16
[ CPUIntType{1} ]
mel lengths shape
 17
[ CPUIntType{1} ]
mel lengths shape
 18
[ CPUIntType{1} ]
mel lengths shape
 19
[ CPUIntType{1} ]
mel lengths shape
 20
[ CPUIntType{1} ]
mel lengths shape
 21
[ CPUIntType{1} ]
mel lengths shape
 22
[ CPUIntType{1} ]
mel lengths shape
 23
[ CPUIntType{1} ]
mel lengths shape
 24
[ CPUIntType{1} ]
mel length

 216
[ CPUIntType{1} ]
mel lengths shape
 217
[ CPUIntType{1} ]
mel lengths shape
 218
[ CPUIntType{1} ]
mel lengths shape
 219
[ CPUIntType{1} ]
mel lengths shape
 220
[ CPUIntType{1} ]
mel lengths shape
 221
[ CPUIntType{1} ]
mel lengths shape
 222
[ CPUIntType{1} ]
mel lengths shape
 223
[ CPUIntType{1} ]
mel lengths shape
 224
[ CPUIntType{1} ]
mel lengths shape
 225
[ CPUIntType{1} ]
mel lengths shape
 226
[ CPUIntType{1} ]
mel lengths shape
 227
[ CPUIntType{1} ]
mel lengths shape
 228
[ CPUIntType{1} ]
mel lengths shape
 229
[ CPUIntType{1} ]
mel lengths shape
 230
[ CPUIntType{1} ]
mel lengths shape
 231
[ CPUIntType{1} ]
mel lengths shape
 232
[ CPUIntType{1} ]
mel lengths shape
 233
[ CPUIntType{1} ]
mel lengths shape
 234
[ CPUIntType{1} ]
mel lengths shape
 235
[ CPUIntType{1} ]
mel lengths shape
 236
[ CPUIntType{1} ]
mel lengths shape
 237
[ CPUIntType{1} ]
mel lengths shape
 238
[ CPUIntType{1} ]
mel lengths shape
 239
[ CPUIntType{1} ]
mel lengths shape
 240
[ CPUIntTyp

(tensor([[[-5.3608, -4.5817, -3.9340,  ..., -3.0448, -3.4721, -3.0374],
          [-5.3771, -4.1494, -3.0044,  ..., -2.9240, -3.3496, -2.9618],
          [-5.4169, -3.8461, -2.3862,  ..., -3.4445, -3.9021, -3.3215],
          ...,
          [-9.1931, -9.1417, -7.9920,  ..., -8.5886, -9.2550, -7.9324],
          [-9.2547, -9.1907, -7.7566,  ..., -8.6550, -9.4180, -7.8738],
          [-9.2874, -9.1192, -7.6428,  ..., -8.6703, -9.4088, -7.8822]]],
        grad_fn=<TransposeBackward0>),
 tensor([[[-5.3216, -4.6225, -4.0178,  ..., -3.0831, -3.4707, -3.0251],
          [-5.3460, -4.2010, -3.0768,  ..., -2.9786, -3.3423, -2.9427],
          [-5.3890, -3.8589, -2.3906,  ..., -3.5215, -3.8695, -3.2913],
          ...,
          [-9.4541, -9.2785, -7.9482,  ..., -8.7639, -9.2367, -7.8806],
          [-9.4932, -9.2630, -7.6971,  ..., -8.8277, -9.4014, -7.8313],
          [-9.5041, -9.1706, -7.5261,  ..., -8.8376, -9.3934, -7.8285]]],
        grad_fn=<AddBackward0>),
 tensor([[-12.1378, -12.1329, 

In [13]:
input_[0]

tensor([[ 91,  73,  11, 116, 144, 109, 116,  11,  88, 130,  82, 119,  11, 104,
          66, 116, 131,  11, 115,  74, 118, 129, 133,  11, 123, 143,  97,  11,
          91,  73,  11, 117, 102, 146, 112,  11,  90,  78, 105,  11,  73, 119,
          90,  11,  91,  94, 119,  11, 129, 141, 129, 133,  11, 108, 119,  11,
         118,  86,  11, 118,  82,  91,   7]])

In [14]:

torch.onnx.export(
    scripted_module,
    input_,
    "test.onnx", 
    verbose=True, 
    opset_version=15,
    dynamic_axes=dict(
        mel_out={0: "batch_size", 2: "output_length"}, 
        mel_postnet={0: "batch_size", 2: "output_length"}, 
        gate={0: "batch_size", 1: "output_length"}, 
        attn={0: "batch_size", 1: "output_length", 2: "sequence_length"},
        INPUT_0={0: "batch_size", 1: "sequence_length"},
        #mel_lengths={0: "batch_size"},
        # mel_out={0: "batch_size", 1: "sequence_length"}
    ),
    input_names=["INPUT_0", "input_lengths", "speaker_id", "gst"],
    # output_names=["OUTPUT_0"] # , "output_lengths", "output_speaker_id", "output_gst"],
    output_names=["mel_out", "mel_postnet", "gate", "attn"]# , "mel_lenghts"], #, "output_frames"],
)

/usr/local/lib/python3.8/site-packages/torch/onnx/symbolic_opset9.py:2188: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with LSTM can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  warnings.warn("Exporting a model to ONNX with a batch_size other than 1, " +
/usr/local/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py:719: UserWarning: allowzero=0 by default. In order to honor zero value in shape use allowzero=1
  warnings.warn("allowzero=0 by default. In order to honor zero value in shape use allowzero=1")
/usr/local/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py:773: UserWarning: ONNX export mode is set to inference mode, but operator dropout is set to training  mode. The operators will be exported in training , as specified by the functional operator.
  warnings.warn("ONNX expor

mel lengths shape
 0
[ CPUIntType{1} ]
mel lengths shape
 1
[ CPUIntType{1} ]
mel lengths shape
 2
[ CPUIntType{1} ]
mel lengths shape
 3
[ CPUIntType{1} ]
mel lengths shape
 4
[ CPUIntType{1} ]
mel lengths shape
 5
[ CPUIntType{1} ]
mel lengths shape
 6
[ CPUIntType{1} ]
mel lengths shape
 7
[ CPUIntType{1} ]
mel lengths shape
 8
[ CPUIntType{1} ]
mel lengths shape
 9
[ CPUIntType{1} ]
mel lengths shape
 10
[ CPUIntType{1} ]
mel lengths shape
 11
[ CPUIntType{1} ]
mel lengths shape
 12
[ CPUIntType{1} ]
mel lengths shape
 13
[ CPUIntType{1} ]
mel lengths shape
 14
[ CPUIntType{1} ]
mel lengths shape
 15
[ CPUIntType{1} ]
mel lengths shape
 16
[ CPUIntType{1} ]
mel lengths shape
 17
[ CPUIntType{1} ]
mel lengths shape
 18
[ CPUIntType{1} ]
mel lengths shape
 19
[ CPUIntType{1} ]
mel lengths shape
 20
[ CPUIntType{1} ]
mel lengths shape
 21
[ CPUIntType{1} ]
mel lengths shape
 22
[ CPUIntType{1} ]
mel lengths shape
 23
[ CPUIntType{1} ]
mel lengths shape
 24
[ CPUIntType{1} ]
mel length

mel lengths shape
 214
[ CPUIntType{1} ]
mel lengths shape
 215
[ CPUIntType{1} ]
mel lengths shape
 216
[ CPUIntType{1} ]
mel lengths shape
 217
[ CPUIntType{1} ]
mel lengths shape
 218
[ CPUIntType{1} ]
mel lengths shape
 219
[ CPUIntType{1} ]
mel lengths shape
 220
[ CPUIntType{1} ]
mel lengths shape
 221
[ CPUIntType{1} ]
mel lengths shape
 222
[ CPUIntType{1} ]
mel lengths shape
 223
[ CPUIntType{1} ]
mel lengths shape
 224
[ CPUIntType{1} ]
mel lengths shape
 225
[ CPUIntType{1} ]
mel lengths shape
 226
[ CPUIntType{1} ]
mel lengths shape
 227
[ CPUIntType{1} ]
mel lengths shape
 228
[ CPUIntType{1} ]
mel lengths shape
 229
[ CPUIntType{1} ]
mel lengths shape
 230
[ CPUIntType{1} ]
mel lengths shape
 231
[ CPUIntType{1} ]
mel lengths shape
 232
[ CPUIntType{1} ]
mel lengths shape
 233
[ CPUIntType{1} ]
mel lengths shape
 234
[ CPUIntType{1} ]
mel lengths shape
 235
[ CPUIntType{1} ]
mel lengths shape
 236
[ CPUIntType{1} ]
mel lengths shape
 237
[ CPUIntType{1} ]
mel lengths shap

In [15]:
!ls -lash test.onnx

108M -rw-r--r-- 1 root root 108M Jun 12 15:31 test.onnx


In [21]:
!pip install --upgrade onnx

You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.


In [17]:
import onnx

In [18]:
onnx_model = onnx.load("test.onnx")

In [19]:
onnx.checker.check_model(onnx_model)